# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-14 04:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ui', '0002_auto_20181112_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(help_text='The spoken version of the pictogram', upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(['mp3'])])),
                ('images', models.ImageField(help_text='The image version of the pictogram', upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['blp', 'bmp', 'bufr', 'cur', 'pcx', 'dcx', 'dds', 'ps', 'eps', 'fit', 'fits', 'fli', 'flc', 'ftc', 'ftu', 'gbr', 'gif', 'grib', 'h5', 'hdf', 'png', 'jp2', 'j2k', 'jpc', 'jpf', 'jpx', 'j2c', 'icns', 'ico', 'im', 'iim', 'tif', 'tiff', 'jfif', 'jpe', 'jpg', 'jpeg', 'mpg', 'mpeg', 'mpo', 'msp', 'palm', 'pcd', 'pdf', 'pxr', 'pbm', 'pgm', 'ppm', 'psd', 'bw', 'rgb', 'rgba', 'sgi', 'ras', 'tga', 'webp', 'wmf', 'emf', 'xbm', 'xpm'])])),
                ('text', models.CharField(help_text='The text version of the pictogram', max_length=255)),
            ],
        ),
    ]
